codecov:
  notify:
    require_ci_to_pass: yes
  token: dc2f3e56-b14d-4376-9bcf-6fc501c4320d

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
